### ISSUE TITLE
Components folder flat structure

### ISSUE THREAD

**Issue by iuriizaporozhets** [Joraz/github-stars#2]
In the task was written to build domain driven project architecture. Current flat structure of the components folder could become a mess from the scalability perspective. Could you revisit this part please? Thanks

**Comment by Joraz** [comment]
Will do

**Comment by Joraz** [comment]
Implemented in commit https://github.com/Joraz/github-stars/commit/2fe67384309a98d8feeaa9e38c0e75d4e4e1c630
