### ISSUE TITLE
Sorting issues

### ISSUE THREAD

**Issue by iuriizaporozhets** [Joraz/github-stars#3]
We don't require sorting to be implemented in test task, but it's good that you have added it. 
Though It's behaviour seems strange to me, it sorts that whole list of repositories, instead of sorting only those on the page.
It would be good it this could be fixed, or sorting removed at all (won't influence on result, but would be good to have), up to you.

**Comment by Joraz** [comment]
I don't know if I necessarily agree about the sorting behaviour being strange, I feel like most multi-page tables I've used act like this.

I'd be happy to create a branch with per-page sorting for you to try though

**Comment by Joraz** [comment]
Branch is at https://github.com/Joraz/github-stars/pull/6. I will remove sorting from the main branch as part of other work
