### ISSUE TITLE
"Nice to have" tasks

### ISSUE THREAD

**Issue by iuriizaporozhets** [Joraz/github-stars#4]
Daniel, I saw that you put a lot of effort in the test task already but I have to ask you for some additional work.
I saw that search is on your todo list, I would be great to have it implemented.|
Same with pagination, it would be great to select specific page (Pagination component from `Mantine` could be used).

Would be good to see usage of styled-components (at least in one place);

**Comment by Joraz** [comment]
I will implement the tag search

**Comment by Joraz** [comment]
Full pagination is a bit trickier due to the GitHub GraphQL api using cursors for paging. There would be no way of knowing, for example, what cursor to use for results if a user wanted to go straight from page 2 to 5, for example

**Comment by Joraz** [comment]
I will replace some of the Mantine layout components with a styled component, for demonstration purposes

**Comment by Joraz** [comment]
Search and css-in-js are in https://github.com/Joraz/github-stars/commit/5e4b0c411c32cdce1f1868e580f0c728489f2e37. 

As mentioned above, I don't think full pagination will be possible with the results returned from GraphQL
